rm -rf /etc/apt/sources.list.d/google-musicmanager.list
rm -rf /etc/apt/sources.list.d/google-musicmanager.list.save
rm -rf /etc/cron.daily/google-musicmanager
rm -rf /etc/default/google-musicmanager
rm -rf /home/user/.config/google-musicmanager
rm -rf /usr/bin/google-musicmanager
rm -rf /usr/share/applications/google-musicmanager.desktop
rm -rf /usr/share/icons/hicolor/128x128/apps/google-musicmanager.png
rm -rf /usr/share/icons/hicolor/16x16/apps/google-musicmanager.png
rm -rf /usr/share/icons/hicolor/32x32/apps/google-musicmanager.png
rm -rf /usr/share/icons/hicolor/48x48/apps/google-musicmanager.png
rm -rf /usr/share/menu/google-musicmanager.menu
rm -rf /var/lib/dpkg/info/google-musicmanager-beta.conffiles
rm -rf /var/lib/dpkg/info/google-musicmanager-beta.list
rm -rf /var/lib/dpkg/info/google-musicmanager-beta.md5sums
rm -rf /var/lib/dpkg/info/google-musicmanager-beta.postinst
rm -rf /var/lib/dpkg/info/google-musicmanager-beta.postrm
rm -rf /var/lib/dpkg/info/google-musicmanager-beta.prerm
